@startuml
scale 350 width

state registration : players: List[Player]
state registration : scoringTokenStacks: ScoringTokenStacks

state settingUp : plantingTreePlayer: Int
state settingUp : playerBoards: List[PlayerBoard]
state settingUp : blocks: List[Block]
state settingUp : scoringTokenStacks: ScoringTokenStacks

state playing : actionPlayer: Int,
state playing : firstPlayerTokenPosition: Int,
state playing : sunLocation: SunLocation,
state playing : day: Int,
state playing : playerBoards: List[PlayerBoard],
state playing : blocks: List[Block],
state playing : scoringTokenStacks: TokenStock

state gameOver : playerBoards: List[PlayerBoard]
state gameOver : blocks: List[Block]

state registration as "Registration"
state settingUp as "Setting Up"
state playing as "Playing"
state gameOver as "Game Over"

[*] -> registration

registration -> registration: addPlayer(player)
registration --> settingUp: startGame

settingUp -> settingUp: placeTree
settingUp --> playing: startPlaying [everyPlayerPlaced2Trees]

playing -> playing: passNextPlayer \n playerSeedPlant \n playerGrowPlant \n buyItem

playing --> gameOver: doneFinalRound


@enduml